using Dapper.Contrib.Extensions;

namespace SCPCRazor.Model
{
    [Table("cadpac")]
    public class cadpacEntity
    {
        public int codpac { get; set; }
        public string ric { get; set; }
        public string cartaosus { get; set; }
        public string proantigo { get; set; }
        public string pasta { get; set; }
        public string nomepac { get; set; }
        public string sexo { get; set; }
        public int codpacpai { get; set; }
        public int codpacmae { get; set; }
        public int codpacconj { get; set; }
        public int codpactit { get; set; }
        public DateTime datanasc { get; set; }
        public string tipodatnas { get; set; }
        public string estadociv { get; set; }
        public string logradouro { get; set; }
        public string tipologr { get; set; }
        public string numlogr { get; set; }
        public string complemen { get; set; }
        public string ceppac { get; set; }
        public string codmun { get; set; }
        public string codbai { get; set; }
        public string foneresid { get; set; }
        public string email { get; set; }
        public string nomepai { get; set; }
        public string nomemae { get; set; }
        public string conjuge { get; set; }
        public string rgpac { get; set; }
        public string ufrgpac { get; set; }
        public string orgrgpac { get; set; }
        public DateTime datargpac { get; set; }
        public string cpfpac { get; set; }
        public string cartrabpac { get; set; }
        public string fonecompac { get; set; }
        public string faxpac { get; set; }
        public string codempresa { get; set; }
        public string planopac { get; set; }
        public string codmunnasc { get; set; }
        public DateTime datentrada { get; set; }
        public string tipocertid { get; set; }
        public string cartorio { get; set; }
        public string livro { get; set; }
        public string folha { get; set; }
        public string termo { get; set; }
        public DateTime datemissao { get; set; }
        public string corpac { get; set; }
        public string instrucao { get; set; }
        public string situtrab { get; set; }
        public string profpac { get; set; }
        public string tiptitular { get; set; }
        public string nomtitular { get; set; }
        public string religiao { get; set; }
        public int filhonum { get; set; }
        public string tipobito { get; set; }
        public DateTime datobito { get; set; }
        public string declobito { get; set; }
        public string localpasta { get; set; }
        public DateTime datcadast { get; set; }
        public DateTime datatualiz { get; set; }
        public string classific { get; set; }
        public string observpac { get; set; }
        public string opecadast { get; set; }
        public string opeatualiz { get; set; }
        public string pispac { get; set; }
        public string cracha { get; set; }
        public string matricpac { get; set; }
        public string matrictit { get; set; }
        public string emirgpac { get; set; }
        public string anopacdos { get; set; }
        public string doadorsg { get; set; }
        public string produto { get; set; }
        public string cbo { get; set; }
        public string cnae { get; set; }
        public string extra01 { get; set; }
        public string extra02 { get; set; }
        public string extra03 { get; set; }
        public string extra04 { get; set; }
        public string extra05 { get; set; }
        public string extra06 { get; set; }
        public string extra07 { get; set; }
        public string extra08 { get; set; }
        public string extra09 { get; set; }
        public string extra10 { get; set; }
        public string extra11 { get; set; }
        public string extra12 { get; set; }
        public string inativo { get; set; }
        public int numultate { get; set; }
        public DateTime datultate { get; set; }
        public int numpenate { get; set; }
        public DateTime datpenate { get; set; }
        public DateTime datultint { get; set; }
        public DateTime datpenint { get; set; }
        public string restricoes { get; set; }
        public DateTime datarevis { get; set; }
        public string operevis { get; set; }
        public string conheceu { get; set; }
        public string codemprpla { get; set; }
        public string codnacion { get; set; }
        public string coduni { get; set; }
        public string titeleitor { get; set; }
        public int digitoterm { get; set; }
        public string celular { get; set; }
        public DateTime validcart { get; set; }
        public string matricert { get; set; }
        public int qtd1 { get; set; }
        public string cartaopre { get; set; }
        public string codetnia { get; set; }
        public string confiden { get; set; }
        public string pronconexa { get; set; }
        public string responcnpj { get; set; }
        public string nomesocial { get; set; }
        public string obsfone { get; set; }
        public string passaporte { get; set; }
        public long codarquivo { get; set; }
        public int idpaclogin { get; set; }
        public string uuid { get; set; }
        public string doispais { get; set; }
        public string emancipa { get; set; }
        public DateTime dtemancipa { get; set; }
    }
    
}
